### ISSUE TITLE
Define MTA or move to Acronym

### ISSUE THREAD

**Issue by bourdett** [commoncriteria/emailclient#12]
currently MTA is defined as Mail Transfer Agent. I think we need to add more of a definition perhaps or move to Acronyms section

http://en.wikipedia.org/wiki/Message_transfer_agent

**Comment by japit** [comment]
MTA will be moved to Acronyms because it's only used one time in the EP in an Application note (below) of MOF. Defining it doesn't seem to add any real value but if we do want it defined I’d say something like:  Relays electronic mail to the message handling service of the Message Delivery Agent (MDA) to be delivered to a local recipient’s inbox

For reference, the Application Note I referred to says: The Administrator is responsible for management activities, including setting the policy that is applied by the enterprise on the email client. This administrator is likely to be acting remotely and could be the MTA administrator acting through a centralized management console or dashboard.
