### ISSUE TITLE
talk to M or other standards mavens about how to treat 'open specifications'

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/emailclient#3]
Yeah, this is the MAPI question.

**Comment by japit** [comment]
For FTP_ITC.1.3 add assignment list to the selection to include [any other protocol].  Also need to say something about authentication since this is about authentication and not about the protocol being used. Perhaps: The email client shall initiate authentication and communication via the trusted channel for [protocol options].

**Comment by japit** [comment]
So far the only update here is an assignment for other protocols was added to account for open specifications.

**Comment by japit** [comment]
Recommend close
